library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5
  - bytestring
  - htoml
  - text
  - system-filepath
  - optparse-applicative
  - persistent
  - parsec
  - aeson
  - servant-server
  - wai
  - warp
  exposed-modules:
  - Lib
  - Config
tests:
  account-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - persona
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
copyright: 2020 Author name here
category: Web
maintainer: example@example.com
name: persona
version: 0.1.0.0
extra-source-files:
- README.md
author: Author name here
github: ardfard/persona
license: BSD3
executables:
  account-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - persona
